"""add conversation fields to questions

Revision ID: 02c5a9a6e50b
Revises: 45039f54c600
Create Date: 2026-08-07 08:34:47.760916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02c5a9a6e50b'
down_revision: Union[str, Sequence[str], None] = '45039f54c600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('answers', sa.Column('feedback', sa.Text(), nullable=True))
    op.add_column('answers', sa.Column('model_answer', sa.Text(), nullable=True))
    op.add_column('answers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'answers', ['question_id'])
    op.drop_column('answers', 'submitted_at')
    op.add_column('questions', sa.Column('question_type', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('sequence_number', sa.Integer(), server_default='1', nullable=False))
    op.add_column('questions', sa.Column('is_follow_up', sa.Boolean(), server_default='false', nullable=True))
    op.drop_column('questions', 'created_at')
    # ### end Alembic commands ###
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('questions', 'is_follow_up')
    op.drop_column('questions', 'sequence_number')
    op.drop_column('questions', 'topic')
    op.drop_column('questions', 'question_type')
    op.add_column('answers', sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answers', type_='unique')
    op.drop_column('answers', 'created_at')
    op.drop_column('answers', 'model_answer')
    op.drop_column('answers', 'feedback')
    op.drop_column('answers', 'score')
    # ### end Alembic commands ###
