"""create Coding Question and Coding Answer and add realtionship with Interview

Revision ID: 45039f54c600
Revises: a4825d81a1b4
Create Date: 2026-08-04 08:20:50.879339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45039f54c600'
down_revision: Union[str, Sequence[str], None] = 'a4825d81a1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
