"""update schema models and constraints

Revision ID: aa7bd7027262
Revises: 02c5a9a6e50b
Create Date: 2026-08-07 10:40:46.892389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7bd7027262'
down_revision: Union[str, Sequence[str], None] = '02c5a9a6e50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'coding_answers', ['question_id'])
    op.create_unique_constraint(None, 'results', ['interview_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='unique')
    op.drop_constraint(None, 'coding_answers', type_='unique')
    # ### end Alembic commands ###
